<?php
namespace Tests\Feature;
use App\Models\Client; use App\Models\MainCategory; use App\Models\PaymentStage; use App\Models\Project; use App\Models\Task; use App\Models\ToolMaterial; use App\Models\Unit; use App\Models\User;
use App\Services\Excel\ExcelImportService; use App\Services\Excel\Imports\PaymentStageImport; use App\Services\Excel\Imports\TaskImport; use App\Services\Excel\Imports\ToolMaterialImport;
use Illuminate\Foundation\Testing\RefreshDatabase; use PhpOffice\PhpSpreadsheet\Spreadsheet; use PhpOffice\PhpSpreadsheet\Writer\Xlsx; use Tests\TestCase;
class AdditionalExcelImportsTest extends TestCase {
 use RefreshDatabase; private User $actor; private Project $project;
 protected function setUp():void { parent::setUp(); $this->actor=User::factory()->create(); Client::create(['name'=>'Client','status'=>'active']); $this->project=Project::create(['name'=>'Project','project_code'=>'P1','client_id'=>1,'type'=>'Build','priority'=>'medium','status'=>'planning']); }
 public function test_payment_stage_import_success_and_history():void { $r=$this->import([['name'],['Milestone']],new PaymentStageImport()); $this->assertSame('completed',$r->status); $this->assertDatabaseHas('payment_stages',['stage_name'=>'Milestone']); }
 public function test_task_import_resolves_project_and_rejects_unknown_project():void { $r=$this->import([['project','title','type','priority','status'],['Project','Task','general','medium','pending']],new TaskImport()); $this->assertSame('completed',$r->status); $bad=$this->import([['project','title','type','priority','status'],['Missing','Bad','general','medium','pending']],new TaskImport()); $this->assertSame('failed',$bad->status); }
 public function test_tool_material_import_resolves_unit_and_rejects_unknown_unit():void { $r=$this->import([['item_type','name','date','unit','opening_quantity','opening_rate'],['material','Cement','2026-01-01','Nos','2','10']],new ToolMaterialImport()); $this->assertSame('completed',$r->status); $bad=$this->import([['item_type','name','date','unit','opening_quantity','opening_rate'],['material','Sand','2026-01-01','BAD','2','10']],new ToolMaterialImport()); $this->assertSame('failed',$bad->status); }
 public function test_required_headers_and_mixed_rows_are_recorded():void { $r=$this->import([['title'],['Bad']],new TaskImport()); $this->assertSame('failed',$r->status); $mixed=$this->import([['project','title','type','priority','status'],['Project','Good','general','medium','pending'],['Missing','Bad','general','medium','pending']],new TaskImport()); $this->assertSame('completed_with_errors',$mixed->status); $this->assertSame(1,$mixed->imported_rows); $this->assertSame(1,$mixed->failed_rows); }
 private function import(array $rows,object $definition):object { $s=new Spreadsheet();$s->getActiveSheet()->fromArray($rows);$p=tempnam(sys_get_temp_dir(),'excel4-').'.xlsx';(new Xlsx($s))->save($p);$r=app(ExcelImportService::class)->run($p,basename($p),$this->actor->id,$definition);@unlink($p);$s->disconnectWorksheets();return $r; }
}
